# Generated by Django 3.0.8 on 2022-01-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211222_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='category',
        ),
        migrations.RemoveField(
            model_name='script',
            name='tags',
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
