# Generated by Django 3.0.8 on 2022-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
