# Generated by Django 3.0.8 on 2022-01-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220122_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
