# Generated by Django 3.0.8 on 2022-01-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220122_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiToken',
            new_name='API_Key',
        ),
    ]
