# Generated by Django 3.0.8 on 2022-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220122_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
