# Generated by Django 3.0.8 on 2022-01-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220122_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='avatars'),
        ),
    ]
