# Generated by Django 3.0.8 on 2022-01-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220123_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-profile.png', null=True, upload_to='avatars'),
        ),
    ]
