# Generated by Django 3.0.8 on 2022-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220225_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='https://drive.google.com/file/d/1qpvYebZHyEW1LBLJ8I8t7-ZnkfFi7A0A/view?usp=sharing'),
        ),
    ]
