# Generated by Django 3.0.8 on 2022-01-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220123_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
