# Generated by Django 3.0.8 on 2022-01-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220123_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
