# Generated by Django 3.0.8 on 2022-01-23 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220123_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.Course'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('display_pic', models.ImageField(upload_to='missions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.Level')),
            ],
            options={
                'ordering': ('mission_id',),
            },
        ),
    ]
