# Generated by Django 3.0.8 on 2022-01-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
