# Generated by Django 3.0.8 on 2022-01-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='UnlockedLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('freq', models.CharField(choices=[('month', 'monthly'), ('year', 'yearly'), ('week', 'weekly')], max_length=20)),
                ('ft_days', models.IntegerField()),
                ('is_best', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currency')),
            ],
        ),
    ]
