# Generated by Django 3.0.8 on 2022-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_currency_subscription_unlockedlevel_unlockedmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('subs_id',)},
        ),
        migrations.AddField(
            model_name='subscription',
            name='sales_tax',
            field=models.IntegerField(default=9),
        ),
    ]
