# Generated by Django 3.0.8 on 2022-01-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220123_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlockedlevel',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='unlockedmission',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
